# Generated by Django 5.0.6 on 2024-06-13 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=255)),
                ('quiz_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('top_score', models.FloatField(default=0)),
                ('score_avg', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('choices', models.JSONField()),
                ('correct_answers', models.JSONField()),
                ('score', models.FloatField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('top_score', models.FloatField()),
                ('score_avg', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuiz',
            fields=[
                ('student_quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.teacher'),
        ),
    ]
