# Generated by Django 5.2.6 on 2025-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
